apiVersion: apps/v1
kind: Deployment
metadata:
  name: approval-processing-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: approval-processing-service
  template:
    metadata:
      labels:
        app: approval-processing-service
    spec:
      containers:
        - name: approval-processing-service
          image: leeych1745/approval-processing-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8083 # HTTP
            - containerPort: 9090 # gRPC
          env:
            - name: GRPC_CLIENT_APPROVAL_REQUEST_SERVICE_ADDRESS
              value: "static://approval-request-service:9091" # Request 서비스 이름 사용

---
apiVersion: v1
kind: Service
metadata:
  name: approval-processing-service
spec:
  type: NodePort
  selector:
    app: approval-processing-service
  ports:
    - name: http
      port: 8083
      targetPort: 8083
      nodePort: 30083
    - name: grpc
      port: 9090
      targetPort: 9090